logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  jsonl_events: true            # NEW: write events.ndjson for SSE replay

io:
  sampling_rate: &sr 5.0        # anchor for reuse
  image_globs: ["*.png", "*.jpg", "*.jpeg"]
  track_glob: "*.npy"
  table_globs: ["*.csv", "*.tsv", "*.xls", "*.xlsx"]

heatmap:
  lower: -1e20
  upper: 1e16
  binarize: true
  origin: lower
  cmap: hot

detrend:
  degree: 1
  min_samples: 0.5
  residual_threshold: null
  random_state: 42

peaks:
  prominence: 3.0
  width: 2
  distance: 8

period:
  sampling_rate: *sr            # use the same value as io.sampling_rate
  min_freq: 0.02
  max_freq: 2.0

viz:
  enabled: true
  per_track:
    detrended_with_peaks: true
    spectrum: true
  summary:
    histograms: true
  wave_windows:                # NEW: tame explosion of tiny files
    save: true                 # save per-peak window PNGs
    max_per_track: 50          # cap count per track
    stride: 1                  # take every Nth window (1 = keep all)
  hist_bins: 20
  dpi: 180

features:
  fit_window_period_frac: 0.5
  classify:
    ripple_max_deg: 10
    surf_min_deg: 20
    prominence_min_px: 1.0

# ----------------------------------------------------
# Service / pipeline controls (NEW)
# ----------------------------------------------------
service:
  partial_every_tracks: 250      # write tracks.partial.json every N tracks
  write_progress_every_secs: 10  # update progress.json cadence
  overlay:
    write_every_tracks: 1
    format: ndjson
  resume:
    enabled: true
    marker_dir: "output/processed"   # per-track .done markers
    progress_file: "progress.json"   # global progress snapshot
    safe_skip: true                  # verify outputs before skipping
  retention:
    enabled: false                   # set true to enable auto-prune
    keep_last_runs: 20
    max_run_age_days: null           # e.g., 14 to age out old runs
  artifacts:
    write_run_json: true             # persist run.json metadata
    write_events_ndjson: true        # append events.ndjson for replay

# ----------------------------------------------------
# KymoButler pipeline configuration
# ----------------------------------------------------
kymo:
  backend: onnx

  onnx:
    # Model & classification/seg behavior
    export_dir: null          # null => auto-discover export/
    seg_size: 256
    force_mode: bi            # "uni" | "bi" | null (null => use classifier)
    fuse_uni_into_bi: true
    fuse_uni_weight: 0.7      # 0.6–0.8 works well

    # Thresholding
    thresholds:
      thr_default: 0.20
      thr_bi: 0.18
      thr_uni: 0.20
    auto_threshold:
      enabled: true
      sweep: [0.12, 0.30, 19]         # [lo, hi, N]
      target_mask_pct: [15.0, 25.0]   # desired mask density band
      trigger_pct: [5.0, 35.0]        # only auto-tune if outside this band
    hysteresis:
      enabled: true
      low: 0.08
      high: 0.18

    # Mask → skeleton shaping
    morphology:
      mode: directional        # "directional" | "classic" | "none"
      directional:
        kv: 5                  # vertical close kernel height (1xkv)
        kh: 5                  # horizontal close kernel width (khx1)
        diag_bridge: true      # apply 3x3 diagonal bridging close
      classic:
        kernel: 3              # 3x3 ellipse; close→open→close

    components:
      min_px: 7                # drop tiny blobs before skeletonization
      min_rows: 5

    skeleton:
      method: thin             # "thin" | "zhangsuen"
      prune_iters: 0
      keep_ratio: 0.60
      keep_min_px: 2000
      prob_floor_min: 0.07     # adapter honors
      prob_floor_max: 0.10     # adapter honors

    # Tracking & post-processing
    tracking:
      min_length: 30
      max_branch_steps: 256
      decision_recent_tail: 16

    postproc:
      extend_rows: 22
      dx_win: 4
      prob_min: 0.11
      max_gap_rows: 13
      max_dx: 6
      prob_bridge_min: 0.11
      dedupe:
        enabled: true
        min_rows: 30
        min_score: 0.11
        overlap_iou: 0.80
        dx_tol: 2.5

    debug:
      save_debug_images: true  # adapter gates file writes on this

  wolfram:
    scripts_dir: kymobutler_scripts
