logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR

io:
  sampling_rate: 5.0
  image_globs: ["*.png", "*.jpg", "*.jpeg"]
  track_glob: "*.npy"
  table_globs: ["*.csv", "*.tsv", "*.xls", "*.xlsx"]   # <- NEW

heatmap:
  lower: -1e20
  upper: 1e16
  binarize: true
  origin: lower
  cmap: hot

detrend:
  degree: 1
  min_samples: 0.5
  residual_threshold: null
  random_state: 42

peaks:
  prominence: 3.0
  width: 2
  distance: 8

period:
  sampling_rate: 5.0
  min_freq: 0.02
  max_freq: 2.0

viz:
  enabled: true
  per_track:
    detrended_with_peaks: true
    spectrum: true
  summary:
    histograms: true
  hist_bins: 20
  dpi: 180

kymo:
  force_mode: bi
  seg_size: 256

  # thresholds
  thr: 0.20
  thr_bi: 0.18       # (was effectively 0.35)
  thr_uni: 0.20

  # WL-like mask→skeleton shaping
  morph_close_open_close: true
  comp_min_px: 5       # relax from 10
  comp_min_rows: 5     # relax from 10
  prune_iters: 2       # relax from 3

  # tracking / save
  min_length: 30

  # bridges weak segments
  hysteresis_enable: true
  hysteresis_low: 0.08
  hysteresis_high: 0.18

  prune_iters: 0

