logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR

io:
  sampling_rate: 5.0
  image_globs: ["*.png", "*.jpg", "*.jpeg"]
  track_glob: "*.npy"
  table_globs: ["*.csv", "*.tsv", "*.xls", "*.xlsx"]   # <- NEW

heatmap:
  lower: -1e20
  upper: 1e16
  binarize: true
  origin: lower
  cmap: hot

detrend:
  degree: 1
  min_samples: 0.5
  residual_threshold: null
  random_state: 42

peaks:
  prominence: 3.0
  width: 2
  distance: 8

period:
  sampling_rate: 5.0
  min_freq: 0.02
  max_freq: 2.0

viz:
  enabled: true
  per_track:
    detrended_with_peaks: true
    spectrum: true
  summary:
    histograms: true
  hist_bins: 20
  dpi: 180
