logging:
  level: INFO
  jsonl_events: true

io:
  sampling_rate: &sr 5.0
  image_globs: ["*.png", "*.jpg", "*.jpeg"]
  track_glob: "*.npy"
  table_globs: ["*.csv", "*.tsv", "*.xls", "*.xlsx"]

heatmap:
  lower: -1e20
  upper: 1e16
  binarize: true
  origin: lower
  cmap: hot

detrend:
  degree: 1
  min_samples: 0.5
  residual_threshold: null
  random_state: 42

peaks:
  prominence: 3.0
  width: 2
  distance: 8

period:
  sampling_rate: *sr
  min_freq: 0.02
  max_freq: 2.0

viz:
  enabled: true
  per_track:
    detrended_with_peaks: true
    spectrum: true
  summary:
    histograms: true
  wave_windows:
    save: true
    max_per_track: 50
    stride: 1
  hist_bins: 20
  dpi: 180

features:
  fit_window_period_frac: 0.5
  classify:
    ripple_max_deg: 10
    surf_min_deg: 20
    prominence_min_px: 1.0

service:
  partial_every_tracks: 250
  write_progress_every_secs: 10
  overlay:
    write_every_tracks: 1
    format: ndjson
  resume:
    enabled: true
    marker_dir: "output/processed"
    progress_file: "progress.json"
    safe_skip: true
  retention:
    enabled: false
    keep_last_runs: 20
    max_run_age_days: null
  artifacts:
    write_run_json: true
    write_events_ndjson: true

kymo:
  backend: onnx

  onnx:
    export_dir: null
    seg_size: 256
    force_mode: bi
    fuse_uni_into_bi: true
    fuse_uni_weight: 0.6          # ↓ less weight on UNI to reduce fuzzy fill

    thresholds:
      thr_default: 0.20
      thr_bi: 0.19                # ↑ slightly stricter to thin mask a touch
      thr_uni: 0.20
    auto_threshold:
      enabled: true
      sweep: [0.12, 0.30, 19]
      target_mask_pct: [15.0, 25.0]
      trigger_pct: [5.0, 35.0]
    hysteresis:
      enabled: true
      low: 0.09                   # ↑ require stronger support for weak pixels
      high: 0.18

    morphology:
      mode: directional
      directional:
        kv: 4                      # ↓ a bit gentler closing to avoid over-bridging
        kh: 4
        diag_bridge: false         # ↓ disable diagonal bridging (common source of hair)
      classic:
        kernel: 3

    components:
      min_px: 9                    # ↑ drop more tiny blobs
      min_rows: 7                  # ↑ require taller components

    skeleton:
      method: thin
      prune_iters: 1               # ↑ trim short stubs post-thinning
      keep_ratio: 0.65             # ↑ protect against over-pruning
      keep_min_px: 2500            # ↑ absolute floor
      prob_floor_min: 0.09         # ↑ raise corridor floor to shave wisps
      prob_floor_max: 0.10

    tracking:
      min_length: 50
      max_branch_steps: 256
      decision_recent_tail: 16

    postproc:
      extend_rows: 22
      dx_win: 4
      prob_min: 0.12               # ↑ be pickier when extending ends
      max_gap_rows: 11             # ↓ merge across slightly smaller gaps
      max_dx: 5                    # ↓ require closer alignment
      prob_bridge_min: 0.12        # ↑ need stronger bridge evidence
      dedupe:
        enabled: true
        min_rows: 30
        min_score: 0.12            # ↑ remove low-quality dupes
        overlap_iou: 0.85          # ↑ stricter duplicate definition
        dx_tol: 2.0                # ↓ tracks must align tighter

    debug:
      save_debug_images: true

  wolfram:
    scripts_dir: kymobutler_scripts
